print('Initials in block letters')
print('Hi, my name is Jorge Bencomo and this program will display mi name initials in block lettters.')
print("""This isn't boring at all!""")
print()
print("           JJJ          BBBBBBB")
print("           JJJ          BBB    BB")
print("           JJJ          BBB    BB")
print("           JJJ          BBB   BB")
print("           JJJ          BBB  BB")
print("           JJJ          BBBBB")
print("           JJJ          BBBBB")
print("           JJJ          BBB  BB")
print("         JJJJJ          BBB   BB")
print("  JJ    JJJJJJ          BBB    BB")
print("   JJ   JJJJJJ          BBB    BB")
print("    JJJJJJJJJJ          BBBBBBBBB")