print("A letter to my future self")
print("For the time being you're only using the print function of python")
print("It's the simplest one of them all but not the least important!")
print("Here's a reminder fot you and your family of all the effort that you're putting into this")
print("Hoping for a better future where you can provide and enjoy life")
print("Laura, mi amor, esto lo hago por ti. Te amo.")
print("Older me: Remember to use the print() function to help with readability!")
print("I love my family and my friends")
print("Fav. emoji is this one: 🫥")